name: bb_assignment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.3.4 <4.0.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.6

  # DI
  get_it: ^7.7.0
  injectable: ^2.4.2

  # network
  dio: ^5.4.3+1

  # local storage
  hive_flutter: ^1.1.0

  # cache image
  cached_network_image: ^3.3.1

  # auto gen
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  retrofit: ^4.1.0

  # logger in console
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500